from enum import Enum


class ErrorCode(str, Enum):
    INVALID_CURRENCY = "INVALID_CURRENCY"
    INVALID_STORE = "INVALID_STORE"
    MISSING_MATERIAL = "MISSING_MATERIAL"
    MISSING_MASTER_DATA = "MISSING_MASTER_DATA"
    QUANTITY_VALIDATION_ERROR = "QUANTITY_VALIDATION_ERROR"
    DUPLICATE_TRANSACTION = "DUPLICATE_TRANSACTION"
    MAPPING_ERROR = "MAPPING_ERROR"
    INTERFACE_TIMEOUT = "INTERFACE_TIMEOUT"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    REMEDIATION_PENDING = "REMEDIATION_PENDING"
    REMEDIATED = "REMEDIATED"
    CLOSED = "CLOSED"