"""initial schema

Revision ID: bf52ca373aea
Revises: 
Create Date: 2026-09-13 03:13:39.737394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf52ca373aea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface_incidents', sa.Column('investigation_started_at', sa.DateTime(), nullable=True))
    op.add_column('interface_incidents', sa.Column('remediation_started_at', sa.DateTime(), nullable=True))
    op.add_column('interface_incidents', sa.Column('remediated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface_incidents', 'remediated_at')
    op.drop_column('interface_incidents', 'remediation_started_at')
    op.drop_column('interface_incidents', 'investigation_started_at')
    # ### end Alembic commands ###
